celery_form/urls.py
from django.urls import path

from .views import another_page, contact_form, note_form


app_name = 'celery_form'
urlpatterns = [
    path('', note_form, name='index'),
    path('contact/', contact_form, name='contact'),
    path('another_page/', another_page, name='another_page')
]

hillels_django_celery/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('celery_forms/', include('celery_form.urls')),
]

celery_form/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    birthday = models.DateField()

    def __str__(self):
        return self.name


class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

celery_form/forms.py
from datetime import timedelta

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone


class PostForm(forms.Form):
    subject = forms.CharField(label='Name', max_length=30)
    email_recipient = forms.EmailField(label='Email', max_length=30)
    message = forms.CharField(label='Text', max_length=300)
    date_and_time = forms.DateTimeField(
        input_formats=['%Y-%m-%d %H:%M%S'],
        help_text='Year-month-day Hour:Min:Sec',
        initial=timezone.now()
    )

    def clean_date_and_time(self):
        data = self.cleaned_data['date_and_time']
        if not timezone.now() < data < timezone.now() + timedelta(days=2):
            raise ValidationError('Датавремя не может быть в прошлом, и не может быть более чем на 2 дня вперед.')
        return data


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=30)
    email = forms.EmailField(label='Email', max_length=30)
    message = forms.CharField(label='Сообщение', max_length=300)

celery_form/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string

from .forms import ContactForm, PostForm
from .tasks import send_contact, send_task


def note_form(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            email_recipient = form.cleaned_data['email_recipient']
            message = form.cleaned_data['message']
            deadline = form.cleaned_data['date_and_time']
            send_task.apply_async((subject, email_recipient, message), eta=deadline)
            return redirect('celery_form:index')
    else:
        form = PostForm()
    return render(
        request,
        'celery_form/index.html',
        {
            'note_form': form}
        )


def another_page(request):
    return render(request, 'celery_form/another_page.html')


def contact(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_contact.delay(name, email, message)
            data['form_is_valid'] = True
            msg = [f"Сообщение от {name} отправлено"]
            data['msg_list'] = render_to_string('celery_form/messages.html', {
                'messages': msg
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
    else:
        form = ContactForm()
    return contact(request, form, 'celery_form/contact.html')

celery_form/templates/celery_form/another_page.html
{% extends 'celery_form/base.html' %}

{% block content %}
<div>
    <p>Thats all folks</p>
</div>

<p><a href="{% url 'celery_form:index' %}">Назад</a></p>
{% endblock %}

celery_form/templates/celery_form/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script src="{% static 'js/contact.js' %}"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'celery_form:index' %}">Index</a>
        <a class="navbar-brand" href="{% url 'celery_form:another_page' %}">Another page</a>
        <button type="button" class="navbar-btn btn-primary js-contact-form " data-bs-toggle="modal" data-bs-target="#modal-contact" data-url="{% url 'celery_form:contact' %}">
            <span class="glyphicon glyphicon-plus"></span>
            Contact
        </button>
      </div>
    </nav>

    <div class="container-fluid p-0" id="popup-messages-content">
        {% include 'celery_form/messages.html' %}
    </div>
    {% block content %}
    {% endblock %}

  <div class="modal fade" id="modal-contact">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
  </div>
</body>
</html>

celery_form/templates/celery_form/contact.html
<form method="post" action="{% url 'celery_form:contact' %}" class="js-contact-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Напишите нам</h4>

  </div>
  <div class="modal-body">
    {% include 'celery_form/contact_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary">Отправить отзыв</button>
  </div>
</form>

celery_form/templates/celery_form/contact_form.html
{% load widget_tweaks %}
{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class+="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class+="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class+="form-control" %}
    {% endif %}
  </div>
{% endfor %}

celery_form/templates/celery_form/index.html
{% extends 'celery_form/base.html' %}
{% block title %}
Index Page
{% endblock %}
{% block content %}
    {% if data.form_is_valid %}
    <p id="succes_email">{{ message }}Должно быть здесь</p>
    {% endif %}
    <form action="{% url 'celery_form:index' %}" method="post">
        {% csrf_token %}
        {{ note_form.as_p }}
        <input type="submit" name="submit" value="OK">
    </form>
    <p><a href="{% url 'celery_form:index' %}">Назад</a></p>

{% endblock %}

celery_form/templates/celery_form/messages.html
{% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert" >
        {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
        </button>
        </div>
{% endfor %}